config/routes.rb
ToDo::Application.routes.draw do
	root :to => 'to_do_lists#index'
  resource :users
	resources :to_do_lists do
  	resources :to_do_items
  end
  controller :sessions do
		get 'login' => :new
		post 'login' => :create
		get 'logout' => :destroy
end

  
  match '*a', :to => 'errors#index'
end

app/models/to_do_list.rb
class ToDoList < ActiveRecord::Base
  attr_accessible :name, :priority
  has_many :to_do_items
  belongs_to :user
  validates :priority, inclusion: PRIORITY
  validates :name, presence: true
  
  def belongs_to_current_user?(curr_user)
  	self.user_id == curr_user.id 
  end
end

app/controllers/to_do_lists_controller.rb
class ToDoListsController < ApplicationController
  # GET /to_do_lists
  # GET /to_do_lists.json
  before_filter :current_user
  rescue_from ActiveRecord::RecordNotFound, :with => :redirect_if_not_found
  
  def index
  	@user = current_user
  	@to_do_lists = ToDoList.where(:user_id => @user.id)
		respond_to do |format|
    	format.html # index.html.erb
    	format.json { render json: @to_do_lists }
    end
  end

  # GET /to_do_lists/1
  # GET /to_do_lists/1.json
  def show
		@to_do_list = ToDoList.find(params[:id])
	 	if(@to_do_list.user_id == current_user.id)
		  respond_to do |format|
		    format.html # show.html.erb
		    format.json { render json: @to_do_list }
		  end
		else
		 	redirect_to to_do_lists_path
		end
  end
	# GET /to_do_lists/new
  # GET /to_do_lists/new.json
  def new
    @to_do_list = ToDoList.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @to_do_list }
    end
  end

  # GET /to_do_lists/1/edit
  def edit
    @to_do_list = ToDoList.find(params[:id])
   	redirect_to to_do_lists_path if(@to_do_list.user_id != current_user.id)
  end

  # POST /to_do_lists
  # POST /to_do_lists.json
  def create
    @to_do_list = ToDoList.new(params[:to_do_list])
    @to_do_list.user_id = current_user.id
    respond_to do |format|
      if @to_do_list.save
      	format.html { 
        	flash[:notice]="To do list was successfully created."
        	render 'show'
        }
        format.json { render json: @to_do_list, status: :created, location: @to_do_list }
      else
        format.html { render action: "new" }
        format.json { render json: @to_do_list.errors, status: :unprocessable_entity }
      end
    end
  end

	# PUT /to_do_lists/1
  # PUT /to_do_lists/1.json
  def update
  	@to_do_list = ToDoList.find(params[:id])
  	@user = current_user
		respond_to do |format|
			if @to_do_list.belongs_to_current_user?(current_user)
			  if @to_do_list.update_attributes(params[:to_do_list])
			    format.html {
			    	redirect_to action: 'index'
			    }
			    format.json { head :no_content }
			  else
			    format.html { 
			    	flash[:notice] = "Error updating #{@to_do_list.name}."
			    	render action: "edit" 
			    }
			  end
			end
  	end
  end

  # DELETE /to_do_lists/1
  # DELETE /to_do_lists/1.json
  def destroy
  	@to_do_list = ToDoList.find(params[:id])
  	@to_do_list.destroy if @to_do_list.belongs_to_current_user?(current_user)
	  redirect_to to_do_lists_url
  end
  
  private
  def redirect_if_not_found
  	@user = current_user
  	redirect_to to_do_lists_path, notice: 'Requested resource does not exists.'
  end
end

app/helpers/to_do_lists_helper.rb
module ToDoListsHelper
end

app/views/to_do_lists/_form.html.erb
<%= form_for(@to_do_list) do |f| %>
 
  <%= errors_for(@to_do_list, 'cant create the List').html_safe %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.select :priority, ToDoList::PRIORITY, prompt: "Priority" %>
  </div>

  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/to_do_lists/edit.html.erb
<h1>Editing to_do_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @to_do_list %> |
<%= link_to 'Back', to_do_lists_path %>

app/views/to_do_lists/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Your ToDos : </h1>

<table>
  <tr>
  <th>Name</th>
  <th>Priority</th>
    <th>Actions</th>
  </tr>

<% @to_do_lists.each do |to_do_list| %>
  <tr>
  	<td><%= to_do_list.name %>
  	<td><%= to_do_list.priority %>
    <td><%= link_to 'Show', to_do_list %>
    <%= link_to 'Edit', edit_to_do_list_path(to_do_list) %>
    <%= link_to 'Destroy', to_do_list, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New To do list', new_to_do_list_path %>

app/views/to_do_lists/new.html.erb
<h1>New to_do_list</h1>
<%= form_for(@to_do_list, :url=> to_do_lists_path) do |f| %> 
<%= render 'form' %>
<% end %>
<%= link_to 'Back', to_do_lists_path %>

app/views/to_do_lists/show.html.erb
<p id="notice"><%= notice %></p>
<h1> <%= @to_do_list.name %> >> Items</h1>
<table border = 1>
<tr>
<th>Subject</th>
<th>Content</th>
<th>Priority</th>
<th>Remind At</th>
<th>Remind On</th>
<th>Actions</th>
</tr>

<% @to_do_list.to_do_items.each do |item| %>
<tr>
<td> <%= item.subject %> </td>
<td> <%= item.content %> </td>
<td> <%= item.priority %> </td>
<td> <%= item.remind_at.strftime("%H:%M:%S")  %> </td>
<td> <%= item.remind_on %> </td>
<td>
	<%= link_to 'Show', to_do_list_to_do_item_path(@to_do_list,item) %>
  <%= link_to 'Edit', edit_to_do_list_to_do_item_path(@to_do_list, item) %>
  <%= link_to 'Destroy', to_do_list_to_do_item_path(@to_do_list, item), confirm: 'Are you sure?', method: :delete %></td>
</td>
</tr>
<% end %>
</table>
<%= link_to 'Add Item', new_to_do_list_to_do_item_path(@to_do_list) %> |
<%= link_to 'Back', to_do_lists_path %>